#!/usr/bin/env bash
#
# Compatibility matrix maintenance: compare docs CSV vs PyPI, run tests, merge RST into CSV,
# optional auto-PR. Subcommands: check_and_update_and_submit | update_matrix | check_matrix.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../../../" && pwd)"

# =============================================================================
# Paths & generated artifacts
# =============================================================================
# default_out_file: compat_matrix.rst path (OUT_FILE or default).
default_out_file() {
    echo "${OUT_FILE:-${SCRIPT_DIR}/../compat_matrix.rst}"
}

# default_compatibility_csv: docs CSV path (COMPATIBILITY_CSV or default).
default_compatibility_csv() {
    echo "${COMPATIBILITY_CSV:-${SCRIPT_DIR}/../../../../docs/source/getting_started/installation_compatibility.csv}"
}

# cleanup_generated_matrix: rm compat_matrix.rst if present.
cleanup_generated_matrix() {
    local out_file
    out_file="$(default_out_file)"
    if [[ -f "${out_file}" ]]; then
        rm -f "${out_file}"
        echo "[INFO] Removed generated matrix file: ${out_file}"
    fi
}

# =============================================================================
# GitHub (optional PR after merge)
# =============================================================================
# repo_slug_from_origin_url: $1 remote URL -> owner/repo for GitHub API.
repo_slug_from_origin_url() {
    local url="${1%.git}"

    if [[ "$url" == git@github.com:* ]]; then
        url="${url#git@github.com:}"
    elif [[ "$url" == https://github.com/* ]]; then
        url="${url#https://github.com/}"
    elif [[ "$url" == http://github.com/* ]]; then
        url="${url#http://github.com/}"
    elif [[ "$url" == ssh://git@github.com/* ]]; then
        url="${url#ssh://git@github.com/}"
    fi

    echo "$url"
}

# maybe_auto_submit_pr: if AUTO_SUBMIT_PR, branch/commit/push CSV and open PR (else no-op).
maybe_auto_submit_pr() {
    # Only runs in CI when explicitly enabled.
    if [[ "${AUTO_SUBMIT_PR:-false}" != "true" ]]; then
        return 0
    fi

    # Avoid creating PRs from PR builds.
    if [[ "${BUILDKITE_PULL_REQUEST:-false}" != "false" ]]; then
        echo "[INFO] BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}; skipping auto PR submission."
        return 0
    fi

    local token="${GITHUB_TOKEN:-${GH_TOKEN:-}}"
    if [[ -z "$token" ]]; then
        echo "[WARN] GITHUB_TOKEN/ GH_TOKEN not set; skipping auto PR submission."
        return 0
    fi

    command -v curl >/dev/null 2>&1 || {
        echo "[WARN] curl not found; skipping auto PR submission."
        return 0
    }

    # Preserve generated matrix output across branch checkouts.
    local out_file compatibility_csv
    out_file="$(default_out_file)"
    compatibility_csv="$(default_compatibility_csv)"

    [[ -f "${out_file}" ]] || {
        echo "[ERROR] Compatibility matrix file not found: ${out_file}" >&2
        exit 1
    }
    [[ -f "${compatibility_csv}" ]] || {
        echo "[ERROR] Compatibility CSV not found: ${compatibility_csv}" >&2
        exit 1
    }

    local tmp_out
    tmp_out="$(mktemp)"
    cp "${out_file}" "${tmp_out}"

    cd "${REPO_ROOT}"

    local base_branch="${PR_BASE_BRANCH:-dev}"
    local build_id="${BUILDKITE_BUILD_ID:-${BUILDKITE_JOB_ID:-$(date +%s)}}"
    local branch="${PR_BRANCH_PREFIX:-ci-compat-matrix-update}-${build_id}"

    # Restore a known good base ref to keep the PR diff focused.
    git fetch origin "${base_branch}" >/dev/null 2>&1 || true
    if git rev-parse --verify "origin/${base_branch}" >/dev/null 2>&1; then
        git checkout -B "${branch}" "origin/${base_branch}"
    else
        git checkout -B "${branch}"
    fi

    cp "${tmp_out}" "${out_file}"
    rm -f "${tmp_out}"

    # Generate docs changes on the new branch.
    update_matrix

    local compatibility_csv_rel="${compatibility_csv#${REPO_ROOT}/}"
    if git diff --quiet -- "${compatibility_csv_rel}"; then
        echo "[INFO] installation_compatibility.csv unchanged after update_matrix; no PR created."
        return 0
    fi

    local commit_msg="${PR_COMMIT_MESSAGE:-chore: update compatibility matrix}"
    local pr_title="${PR_TITLE:-[CI] Update vLLM/LMCache compatibility matrix}"
    local pr_body="${PR_BODY:-Automatically generated by .buildkite/k3_tests/compatible tests.}"

    git config user.name "${PR_BOT_NAME:-lmcache-ci-bot}"
    git config user.email "${PR_BOT_EMAIL:-lmcache-ci@example.com}"

    git add "${compatibility_csv_rel}"
    git commit -m "${commit_msg}"

    local origin_url repo_slug owner encoded_token push_url
    origin_url="$(git remote get-url origin 2>/dev/null || true)"
    repo_slug="$(repo_slug_from_origin_url "${origin_url}")"

    if [[ -z "${repo_slug}" ]]; then
        echo "[ERROR] Could not infer GitHub repo slug from origin URL: ${origin_url}" >&2
        exit 1
    fi

    owner="${repo_slug%/*}"
    encoded_token="$(python3 -c 'import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1], safe=""))' "${token}")"
    push_url="https://x-access-token:${encoded_token}@github.com/${repo_slug}.git"

    # Push using token-authenticated URL (restore origin afterwards).
    git remote set-url origin "${push_url}"
    git push -u origin "${branch}"
    [[ -n "${origin_url}" ]] && git remote set-url origin "${origin_url}" || true

    local github_api="${GITHUB_API_URL:-https://api.github.com}"

    # If a PR already exists for this branch, don't create duplicates.
    local existing_pr_url
    existing_pr_url="$(
        curl -fsSL \
            -H "Authorization: Bearer ${token}" \
            -H "Accept: application/vnd.github+json" \
            "${github_api}/repos/${repo_slug}/pulls?head=${owner}:${branch}&state=open&per_page=1" \
        | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d[0].get("html_url","") if d else "")'
    )"
    if [[ -n "${existing_pr_url}" ]]; then
        echo "[INFO] PR already exists: ${existing_pr_url}"
        return 0
    fi

    local pr_payload pr_url
    pr_payload="$(
        GITHUB_OWNER="${owner}" PR_HEAD_BRANCH="${branch}" PR_BASE_BRANCH="${base_branch}" PR_TITLE="${pr_title}" PR_BODY="${pr_body}" python3 - <<'PY'
import json
import os

title = os.environ["PR_TITLE"]
owner = os.environ["GITHUB_OWNER"]
head_branch = os.environ["PR_HEAD_BRANCH"]
base = os.environ["PR_BASE_BRANCH"]
body = os.environ.get("PR_BODY", "")

print(
    json.dumps(
        {
            "title": title,
            "head": f"{owner}:{head_branch}",
            "base": base,
            "body": body,
            "draft": False,
        }
    )
)
PY
    )"

    pr_url="$(
        curl -fsSL \
            -H "Authorization: Bearer ${token}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -X POST \
            -d "${pr_payload}" \
            "${github_api}/repos/${repo_slug}/pulls" \
        | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("html_url",""))'
    )"

    [[ -n "${pr_url}" ]] || {
        echo "[ERROR] PR creation did not return a URL." >&2
        exit 1
    }

    echo "[INFO] Opened PR: ${pr_url}"
}

# =============================================================================
# PyPI vs CSV: which versions to test
# =============================================================================
# compute_version_sets: CSV vs PyPI -> set VLLM_* / LMCACHE_*_CSV vars; exit if empty.
compute_version_sets() {
    local compatibility_csv
    compatibility_csv="$(default_compatibility_csv)"

    [[ -f "${compatibility_csv}" ]] || {
        echo "[ERROR] Compatibility CSV not found: ${compatibility_csv}" >&2
        exit 1
    }

    local parsed_output line key value
    parsed_output="$(python3 - "${compatibility_csv}" <<'PY'
from __future__ import annotations

from pathlib import Path
import csv
import json
import re
import sys
import urllib.request


def _version_key(version: str) -> tuple[int, int, int]:
    """x.y.z -> int tuple for sorting."""
    return tuple(int(part) for part in version.split("."))


def _released_versions(package: str) -> list[str]:
    """Sorted x.y.z releases from PyPI for package."""
    url = f"https://pypi.org/pypi/{package}/json"
    with urllib.request.urlopen(url, timeout=30) as response:
        payload = json.load(response)

    versions = {
        version
        for version in payload.get("releases", {})
        if re.fullmatch(r"\d+\.\d+\.\d+", version)
    }
    return sorted(versions, key=_version_key)


def _is_later_than_0_8_5(version: str) -> bool:
    """vLLM version > 0.8.5 (cutoff)."""
    return _version_key(version) > (0, 17, 1)


def _is_later_than_0_3_2(version: str) -> bool:
    """LMCache version > 0.3.2 (cutoff)."""
    return _version_key(version) > (0, 4, 1)


compatibility_csv = Path(sys.argv[1])

with compatibility_csv.open(encoding="utf-8", newline="") as f:
    rows = list(csv.reader(f))

existing_vllm: set[str] = set()
existing_lmcache: set[str] = set()
v_key_re = re.compile(r"vLLM\s+(\d+\.\d+(?:\.\d+)?)\.x")

if rows:
    header = rows[0]
    for cell in header[1:]:
        m = re.search(r"LMCache\s+(\d+\.\d+\.\d+)", cell)
        if m and _is_later_than_0_3_2(m.group(1)):
            existing_lmcache.add(m.group(1))
    for row in rows[1:]:
        if not row:
            continue
        vm = v_key_re.search(row[0])
        if not vm:
            continue
        base = vm.group(1)
        norm = base + ".0" if len(base.split(".")) == 2 else base
        if _is_later_than_0_8_5(norm):
            existing_vllm.add(norm)

released_vllm = _released_versions("vllm")
released_lmcache = _released_versions("lmcache")

missing_vllm_bases = [
    version
    for version in released_vllm
    if _is_later_than_0_8_5(version) and version not in existing_vllm
]
missing_lmcache = [
    version
    for version in released_lmcache
    if _is_later_than_0_3_2(version) and version not in existing_lmcache
]

vllm_bases_to_test = (
    sorted(missing_vllm_bases, key=_version_key)
    if len(missing_lmcache) == 0
    else sorted(existing_vllm.union(missing_vllm_bases), key=_version_key)
)
vllm_versions_to_test = [f"{v}.x" for v in vllm_bases_to_test]

lmcache_versions_to_test = (
    sorted(missing_lmcache, key=_version_key)
    if len(missing_vllm_bases) == 0
    else sorted(existing_lmcache.union(missing_lmcache), key=_version_key)
)
missing_vllm_versions = [f"{v}.x" for v in missing_vllm_bases]

print("VLLM_MISSING=" + ",".join(missing_vllm_versions))
print("LMCACHE_MISSING=" + ",".join(missing_lmcache))
print("VLLM_TO_TEST=" + ",".join(vllm_versions_to_test))
print("LMCACHE_TO_TEST=" + ",".join(lmcache_versions_to_test))
PY
)"

    VLLM_MISSING_CSV=""
    LMCACHE_MISSING_CSV=""
    VLLM_TO_TEST_CSV=""
    LMCACHE_TO_TEST_CSV=""

    while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        key="${line%%=*}"
        value="${line#*=}"
        case "$key" in
        VLLM_MISSING) VLLM_MISSING_CSV="$value" ;;
        LMCACHE_MISSING) LMCACHE_MISSING_CSV="$value" ;;
        VLLM_TO_TEST) VLLM_TO_TEST_CSV="$value" ;;
        LMCACHE_TO_TEST) LMCACHE_TO_TEST_CSV="$value" ;;
        esac
    done <<< "${parsed_output}"
  
    # Basic sanity checks to avoid generating an empty matrix.
    if [[ -z "${VLLM_TO_TEST_CSV}" || -z "${LMCACHE_TO_TEST_CSV}" ]]; then
        echo "[INFO] Computed empty version sets (VLLM_TO_TEST/ LMCACHE_TO_TEST)." >&2
        echo "[INFO] Exiting without running tests." >&2
        exit 1
    fi
}

# =============================================================================
# Full pipeline (CI entry)
# =============================================================================
# check_and_update_and_submit: test missing versions, merge CSV, optional PR, cleanup.
check_and_update_and_submit() {
    compute_version_sets

    if [[ -z "${VLLM_MISSING_CSV}" && -z "${LMCACHE_MISSING_CSV}" ]]; then
        echo "[INFO] Compatibility matrix is up-to-date; no missing versions to test."
        cleanup_generated_matrix
        return 0
    fi

    echo "[INFO] Missing vLLM versions (PyPI releases): ${VLLM_MISSING_CSV:-<none>}"
    echo "[INFO] Missing LMCache versions (PyPI releases): ${LMCACHE_MISSING_CSV:-<none>}"

    # We only run tests for versions that are missing, but `update_matrix`
    # merges the results back into `installation_compatibility.csv`.
    env VLLM_VERSIONS="${VLLM_TO_TEST_CSV}" \
        LMCACHE_VERSIONS="${LMCACHE_TO_TEST_CSV}" \
        bash "${SCRIPT_DIR}/run-compatible-test.sh"

    update_matrix
    maybe_auto_submit_pr
    cleanup_generated_matrix
}

# =============================================================================
# Merge generated RST fragment into docs CSV
# =============================================================================
# update_matrix: merge compat_matrix.rst into installation_compatibility.csv (sorted rows/cols).
update_matrix() {
    local out_file compatibility_csv
    out_file="${OUT_FILE:-${SCRIPT_DIR}/../compat_matrix.rst}"
    compatibility_csv="${COMPATIBILITY_CSV:-${SCRIPT_DIR}/../../../../docs/source/getting_started/installation_compatibility.csv}"

    [[ -f "${out_file}" ]] || {
        echo "[ERROR] Compatibility matrix file not found: ${out_file}" >&2
        echo "Run run-compatible-test.sh first, or set OUT_FILE to its output path." >&2
        exit 1
    }

    [[ -f "${compatibility_csv}" ]] || {
        echo "[ERROR] Compatibility CSV not found: ${compatibility_csv}" >&2
        exit 1
    }

    python3 - "${out_file}" "${compatibility_csv}" <<'PY'
from __future__ import annotations

from pathlib import Path
import csv
import io
import re
import sys
from typing import Any


out_file = Path(sys.argv[1])
compatibility_csv = Path(sys.argv[2])


def norm_vllm_base(base: str) -> str:
    """vLLM label token -> merge key (0.11 -> 0.11.0)."""
    parts = base.split(".")
    return f"{base}.0" if len(parts) == 2 else base


def parse_compatibility_csv(path: Path) -> dict[str, Any]:
    """Parse CSV: row/col keys and cell icons."""
    with path.open(encoding="utf-8", newline="") as f:
        rows = list(csv.reader(f))
    if not rows:
        raise SystemExit(f"[ERROR] Empty CSV: {path}")

    header = rows[0]
    lm_labels_in_order: list[str] = []
    lm_keys_in_order: list[str] = []
    lm_label_by_key: dict[str, str] = {}
    for tok in header[1:]:
        m = re.search(r"LMCache\s+(\d+\.\d+(?:\.\d+)?)", tok)
        if not m:
            continue
        lm_key = m.group(1)
        lm_labels_in_order.append(tok)
        lm_keys_in_order.append(lm_key)
        lm_label_by_key[lm_key] = tok

    lm_count = len(lm_keys_in_order)
    if lm_count == 0:
        raise SystemExit("[ERROR] Could not parse LMCache columns from CSV header.")

    v_label_by_key: dict[str, str] = {}
    icons_by_pair: dict[tuple[str, str], str] = {}
    v_keys_in_order: list[str] = []
    v_key_re = re.compile(r"vLLM\s+(\d+\.\d+(?:\.\d+)?)\.x")

    for row in rows[1:]:
        if len(row) < 1 + lm_count:
            continue
        row_label = row[0]
        vm = v_key_re.search(row_label)
        if not vm:
            continue
        v_key = norm_vllm_base(vm.group(1))
        if v_key not in v_label_by_key:
            v_label_by_key[v_key] = row_label
            v_keys_in_order.append(v_key)
        icons = row[1 : 1 + lm_count]
        for lm_key, icon in zip(lm_keys_in_order, icons):
            icons_by_pair[(v_key, lm_key)] = icon

    return {
        "v_keys_in_order": v_keys_in_order,
        "lm_keys_in_order": lm_keys_in_order,
        "v_label_by_key": v_label_by_key,
        "lm_label_by_key": lm_label_by_key,
        "icons_by_pair": icons_by_pair,
    }


def parse_csv_table(lines: list[str]) -> dict[str, Any]:
    """Parse compat_matrix.rst csv-table (same structure as parse_compatibility_csv)."""
    header_line = next((l for l in lines if l.strip().startswith(":header:")), None)
    if not header_line:
        raise SystemExit("[ERROR] Could not locate :header: in csv-table.")

    quoted = re.findall(r'"([^"]*)"', header_line)
    lm_labels_in_order: list[str] = []
    lm_keys_in_order: list[str] = []
    lm_label_by_key: dict[str, str] = {}
    for tok in quoted[1:]:
        m = re.search(r"LMCache\s+(\d+\.\d+(?:\.\d+)?)", tok)
        if not m:
            continue
        lm_key = m.group(1)
        lm_labels_in_order.append(tok)
        lm_keys_in_order.append(lm_key)
        lm_label_by_key[lm_key] = tok

    lm_count = len(lm_keys_in_order)
    if lm_count == 0:
        raise SystemExit("[ERROR] Could not parse LMCache columns from :header:.")

    v_label_by_key: dict[str, str] = {}
    icons_by_pair: dict[tuple[str, str], str] = {}
    v_keys_in_order: list[str] = []

    v_key_re = re.compile(r"vLLM\s+(\d+\.\d+(?:\.\d+)?)\.x")
    for l in lines:
        if "vLLM" not in l or '"' not in l or "," not in l:
            continue
        row = next(
            csv.reader(io.StringIO(l), delimiter=",", quotechar='"', skipinitialspace=True), None
        )
        if not row or len(row) < 1 + lm_count:
            continue

        row_label = row[0]
        vm = v_key_re.search(row_label)
        if not vm:
            continue
        v_key = norm_vllm_base(vm.group(1))

        if v_key not in v_label_by_key:
            v_label_by_key[v_key] = row_label
            v_keys_in_order.append(v_key)

        icons = row[1 : 1 + lm_count]
        for lm_key, icon in zip(lm_keys_in_order, icons):
            icons_by_pair[(v_key, lm_key)] = icon

    return {
        "v_keys_in_order": v_keys_in_order,
        "lm_keys_in_order": lm_keys_in_order,
        "v_label_by_key": v_label_by_key,
        "lm_label_by_key": lm_label_by_key,
        "icons_by_pair": icons_by_pair,
    }


existing_parsed = parse_compatibility_csv(compatibility_csv)

gen_lines = out_file.read_text(encoding="utf-8").splitlines()
start_gen = next((i for i, l in enumerate(gen_lines) if l.strip() == ".. csv-table::"), None)
if start_gen is None:
    raise SystemExit(f"[ERROR] {out_file} does not start with '.. csv-table::' and cannot be used.")

gen_block = gen_lines[start_gen:]
gen_parsed = parse_csv_table(gen_block)

merged_v_order = existing_parsed["v_keys_in_order"] + [
    k for k in gen_parsed["v_keys_in_order"] if k not in existing_parsed["v_keys_in_order"]
]
merged_lm_order = existing_parsed["lm_keys_in_order"] + [
    k for k in gen_parsed["lm_keys_in_order"] if k not in existing_parsed["lm_keys_in_order"]
]

merged_icons = dict(existing_parsed["icons_by_pair"])
merged_icons.update(gen_parsed["icons_by_pair"])

merged_v_labels = dict(existing_parsed["v_label_by_key"])
merged_v_labels.update(gen_parsed["v_label_by_key"])

merged_lm_labels = dict(existing_parsed["lm_label_by_key"])
merged_lm_labels.update(gen_parsed["lm_label_by_key"])


def _version_sort_key(version: str) -> tuple[int, ...]:
    """Semver tuple sort key; newest = largest."""
    return tuple(int(p) for p in version.split("."))


# Newest vLLM top; newest LMCache left.
merged_v_order = sorted(merged_v_order, key=_version_sort_key, reverse=True)
merged_lm_order = sorted(merged_lm_order, key=_version_sort_key, reverse=True)

with compatibility_csv.open("w", encoding="utf-8", newline="") as f:
    w = csv.writer(f)
    w.writerow([""] + [merged_lm_labels[k] for k in merged_lm_order])
    for v_key in merged_v_order:
        v_label = merged_v_labels.get(v_key, f"vLLM {v_key}.x")
        w.writerow(
            [v_label]
            + [merged_icons.get((v_key, lm_key), "❌") for lm_key in merged_lm_order]
        )

print(f"[INFO] Merged {out_file} into {compatibility_csv}")
PY
}

# =============================================================================
# Debug: list PyPI releases missing from CSV
# =============================================================================
# check_matrix: print PyPI-minus-CSV missing versions (debug).
check_matrix() {
    local compatibility_csv
    compatibility_csv="${COMPATIBILITY_CSV:-${SCRIPT_DIR}/../../../../docs/source/getting_started/installation_compatibility.csv}"

    [[ -f "${compatibility_csv}" ]] || {
        echo "[ERROR] Compatibility CSV not found: ${compatibility_csv}" >&2
        exit 1
    }

    local parsed_output line key value
    parsed_output="$(python3 - "${compatibility_csv}" <<'PY'
from pathlib import Path
import csv
import re
import sys
import urllib.request


def _version_key(version: str) -> tuple[int, int, int]:
    """x.y.z -> int tuple for sorting."""
    return tuple(int(part) for part in version.split("."))


def _released_versions(package: str) -> list[str]:
    """Sorted x.y.z releases from PyPI for package."""
    url = f"https://pypi.org/pypi/{package}/json"
    with urllib.request.urlopen(url, timeout=30) as response:
        payload = json.load(response)

    versions = {
        version
        for version in payload.get("releases", {})
        if re.fullmatch(r"\d+\.\d+\.\d+", version)
    }
    return sorted(versions, key=_version_key)


def _is_later_than_0_8_5(version: str) -> bool:
    """vLLM version > 0.8.5 (cutoff)."""
    return _version_key(version) > (0, 8, 5)


def _is_later_than_0_3_2(version: str) -> bool:
    """LMCache version > 0.3.2 (cutoff)."""
    return _version_key(version) > (0, 3, 2)


compatibility_csv = Path(sys.argv[1])

with compatibility_csv.open(encoding="utf-8", newline="") as f:
    rows = list(csv.reader(f))

existing_vllm: set[str] = set()
existing_lmcache: set[str] = set()
v_row_re = re.compile(r"vLLM\s+(\d+\.\d+(?:\.\d+)?)(?:\.x)?")

if rows:
    header = rows[0]
    for cell in header[1:]:
        m = re.search(r"LMCache\s+(\d+\.\d+\.\d+)", cell)
        if m:
            existing_lmcache.add(m.group(1))
    for row in rows[1:]:
        if not row:
            continue
        vm = v_row_re.search(row[0])
        if not vm:
            continue
        base = vm.group(1)
        norm = base + ".0" if len(base.split(".")) == 2 else base
        existing_vllm.add(norm)

missing_vllm = [
    f"{version}.x"
    for version in _released_versions("vllm")
    if _is_later_than_0_8_5(version) and version not in existing_vllm
]
missing_lmcache = [
    version
    for version in _released_versions("lmcache")
    if _is_later_than_0_3_2(version) and version not in existing_lmcache
]

print("VLLM_MISSING=" + ",".join(missing_vllm))
print("LMCACHE_MISSING=" + ",".join(missing_lmcache))
PY
)"

    local -a vllm_versions=()
    local -a lmcache_versions=()
    while IFS= read -r line; do
        key="${line%%=*}"
        value="${line#*=}"
        if [[ "${key}" == "VLLM_MISSING" ]]; then
            [[ -n "${value}" ]] && IFS=',' read -r -a vllm_versions <<< "${value}"
        elif [[ "${key}" == "LMCACHE_MISSING" ]]; then
            [[ -n "${value}" ]] && IFS=',' read -r -a lmcache_versions <<< "${value}"
        fi
    done <<< "${parsed_output}"

    echo "vllm_versions: ${vllm_versions[*]}"
    echo "lmcache_versions: ${lmcache_versions[*]}"
}

# =============================================================================
# CLI
# =============================================================================
# main: dispatch subcommand (default update_matrix).
main() {
    case "${1:-update_matrix}" in
    check_and_update_and_submit|check_and_update)
        check_and_update_and_submit
        ;;
    update|update_matrix)
        update_matrix
        ;;
    check_missing_versions|check_matrix)
        check_matrix
        ;;
    *)
        echo "Usage: $0 [check_and_update_and_submit|check_and_update|update_matrix|check_matrix]" >&2
        exit 1
        ;;
    esac
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    main "$@"
fi
